# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setings_Graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Graph(object):
    def setupUi(self, Dialog_Graph):
        Dialog_Graph.setObjectName("Dialog_Graph")
        Dialog_Graph.resize(300, 430)
        Dialog_Graph.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_3 = QtWidgets.QLabel(Dialog_Graph)
        self.label_3.setGeometry(QtCore.QRect(19, 10, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(3)
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog_Graph)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 360, 75, 23))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog_Graph)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 60, 120, 23))
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setChecked(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(Dialog_Graph)
        self.label_2.setGeometry(QtCore.QRect(10, 400, 261, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_Graph)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Graph)

    def retranslateUi(self, Dialog_Graph):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Graph.setWindowTitle(_translate("Dialog_Graph", "Dialog"))
        self.label_3.setText(_translate("Dialog_Graph", "                     Графік"))
        self.pushButton_4.setText(_translate("Dialog_Graph", "вихід"))
        self.pushButton_5.setText(_translate("Dialog_Graph", "Графік № 1"))
        self.label_2.setText(_translate("Dialog_Graph", "Роботу виконав:Гайдай Назар (1-7 ФІТ)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Graph = QtWidgets.QDialog()
    ui = Ui_Dialog_Graph()
    ui.setupUi(Dialog_Graph)
    Dialog_Graph.show()
    sys.exit(app.exec_())
